import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { PublicLayout } from "@/components/PublicLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/lib/demo-store";
export const Route=createFileRoute("/auth")({component:AuthPage});
function AuthPage(){const navigate=useNavigate();const [mode,setMode]=useState<"signin"|"signup">("signin");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [name,setName]=useState("");const [busy,setBusy]=useState(false);async function onSubmit(e:React.FormEvent){e.preventDefault();setBusy(true);try{if(mode==="signup"){await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});toast.success("Demo account created!")}else{await supabase.auth.signInWithPassword({email,password});toast.success("Welcome back!")}navigate({to:"/my-orders"})}catch(err){toast.error(err instanceof Error?err.message:"Something went wrong")}finally{setBusy(false)}}return <PublicLayout><div className="mx-auto max-w-md px-4 py-20"><div className="glass rounded-3xl p-8"><div className="mb-5 rounded-2xl border border-primary/20 bg-primary/5 p-3 text-xs text-muted-foreground">Demo mode: no real account is created. Any email and password can be used.</div><h1 className="text-3xl">{mode==="signin"?"Sign in":"Create account"}</h1><p className="mt-2 text-sm text-muted-foreground">Use this page to preview the customer account experience.</p><form onSubmit={onSubmit} className="mt-6 space-y-4">{mode==="signup"&&<div className="space-y-1.5"><Label htmlFor="name">Full name</Label><Input id="name" required value={name} onChange={e=>setName(e.target.value)}/></div>}<div className="space-y-1.5"><Label htmlFor="email">Email</Label><Input id="email" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></div><div className="space-y-1.5"><Label htmlFor="password">Password</Label><Input id="password" type="password" required minLength={3} value={password} onChange={e=>setPassword(e.target.value)}/></div><Button type="submit" className="w-full rounded-full" disabled={busy}>{busy?"Please wait…":mode==="signin"?"Sign in":"Create account"}</Button></form><button className="mt-4 w-full text-sm text-muted-foreground underline" onClick={()=>setMode(mode==="signin"?"signup":"signin")}>{mode==="signin"?"New here? Create an account":"Already have an account? Sign in"}</button></div></div></PublicLayout>}
