import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Check } from "lucide-react";
import { PublicLayout } from "@/components/PublicLayout";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { getDemoOrder } from "@/lib/demo-store";
import { STATUS_FLOW, STATUS_LABELS, formatDateTime, rupees } from "@/lib/format";
export const Route=createFileRoute("/order/$code")({component:OrderPage});
function OrderPage(){const {code}=Route.useParams();const {data,isLoading}=useQuery({queryKey:["order",code],queryFn:async()=>getDemoOrder(code),refetchInterval:5000});if(isLoading)return <PublicLayout><div className="mx-auto max-w-2xl px-4 py-16"><Skeleton className="h-80 rounded-3xl"/></div></PublicLayout>;if(!data?.order)return <PublicLayout><div className="mx-auto max-w-lg px-4 py-24 text-center"><div className="glass rounded-3xl p-10"><h1 className="text-2xl">Order not found</h1><p className="mt-2 text-sm text-muted-foreground">This demo order may have been created in another browser.</p><Button className="mt-6 rounded-full" asChild><Link to="/track">Try again</Link></Button></div></div></PublicLayout>;const {order,items}=data;const currentIndex=STATUS_FLOW.indexOf(order.status as any);return <PublicLayout><div className="mx-auto max-w-2xl space-y-6 px-4 py-12"><div className="glass rounded-3xl p-8 text-center"><p className="text-sm text-muted-foreground">Order ID</p><h1 className="font-display text-4xl text-primary">{order.order_code}</h1><p className="mt-2 text-sm text-muted-foreground">Placed {formatDateTime(order.created_at)} · Estimated {order.estimated_delivery_minutes} min</p></div><div className="glass rounded-3xl p-6"><h2 className="text-lg">Status</h2><ol className="mt-4 space-y-4">{STATUS_FLOW.map((step,i)=>{const done=i<=currentIndex;return <li key={step} className="flex items-center gap-3"><span className={`grid size-7 place-items-center rounded-full ${done?"bg-primary text-primary-foreground":"bg-muted"}`}>{done?<Check className="size-4"/>:<span className="text-xs">{i+1}</span>}</span><span className={i===currentIndex?"font-semibold text-primary":"text-muted-foreground"}>{STATUS_LABELS[step]}</span></li>})}</ol></div><div className="glass space-y-3 rounded-3xl p-6"><h2 className="text-lg">Items</h2>{items.map((it:any)=><div key={it.id} className="flex justify-between text-sm"><span>{it.name} × {it.quantity}</span><span>{rupees(Number(it.line_total))}</span></div>)}<div className="space-y-1 border-t border-border pt-3 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{rupees(Number(order.subtotal))}</span></div><div className="flex justify-between"><span>Delivery</span><span>{rupees(Number(order.delivery_charge))}</span></div><div className="flex justify-between font-display text-lg"><span>Total</span><span className="text-primary">{rupees(Number(order.total))}</span></div></div></div><div className="glass rounded-3xl p-6 text-sm"><p>Customer: {order.customer_name}</p><p className="text-muted-foreground">Payment: {order.payment_method==="cod"?"Cash on Delivery":"UPI / Online"}</p></div></div></PublicLayout>}
